### ISSUE TITLE
google maps - label not showing on icon

### ISSUE THREAD

**Issue by kkarol93** [niklasvh/html2canvas#1028]
I have a problem with label which places is on marker icon when I capturing screen of Google Maps.
On version 0.4.0 I have not problem like this, but quality of image is very poor. Each version higher then 0.4.0 doing take a screenshot with better quality but not display label on icon.
I am trying on change  z-index but for any combination this not works. Only when I move manually in DOM element with text above div with icon then  label display on screenshot. But it is not a fix, because it is dom generated by Google Maps API and I cannot replace order in dom by jQuery, there is no any id and class which I can attach.

![image](https://cloud.githubusercontent.com/assets/7278840/21718004/b939b0c2-d414-11e6-8534-6805c5522791.png)

**Comment by jackiekhuu-work** [comment]
I'm having the same problem too. Pls help

**Comment by DanLatimer** [comment]
Why was this issue closed?

**Comment by DanLatimer** [comment]
I figured out a solution. It turned out that this library is respecting the z-indexes but the browser isn't. It's possible that there's some CSS3 attributes google maps uses that makes the labels on top of the icons but you can fix the z-indexes by doing a jquery call. There are two divs siblings, one has all marker labels, the other has the markers. The z-index of the labels is lower than the markers. It turns out even if the child that contains the actual text is a high z-index if it's in a div who's z-index is lower than a sibling all children will be below that sibling no matter their z-index.

I did this for fix it for me:
```
    this.map = $('.gm-style>div:first>div')
    $(this.map[0]).css('z-index', 100);
```
before calling html2canvas. Not a beautiful fix, probably going to break at some point but it got it to work for me in internet explorer, it was already working fine in Chrome for me
