### ISSUE TITLE
All but the very top of the div crops out

### ISSUE THREAD

**Issue by ngduser** [niklasvh/html2canvas#1124]
With the whole image present and visible on screen in the canvas, html2cavas is cropping out most of the bottom of the image. 

Console logs show cropping to a 1401 x 79 image, only showing the very top as a bar. This problem replicates nearly every time html2cavas is used but occasionally will show much more of the canvas and only missing a bit from the bottom.
 
![capture](https://cloud.githubusercontent.com/assets/5769132/25915298/b401be28-3586-11e7-9efe-0e837b433c19.PNG)

The code snippet-

     if (canvas) {
		var saveLink = document.createElement('a');
		saveLink.href = canvas.toDataURL("image/png").replace("image/png", "image/octet-stream");
		saveLink.download = 'name.png';
		saveLink.click();
	}

**Comment by eKoopmans** [comment]
Hi @ngduser, it's possible you're running into the issue of offscreen rendering, which I've created a pull request to address [here](https://github.com/niklasvh/html2canvas/pull/1083). If that is indeed your problem, you might find a solution by using my latest build [here](https://github.com/eKoopmans/html2canvas/tree/develop/dist), which incorporates that PR as well as a few other bugfixes/features.

It's also worth checking that the root element you're sending to html2canvas has the size you think it does, because the final canvas will be cropped to the size of that element. So for instance if that element has a height of only 79px but has `overflow: visible` set, you may see more than 79px of content but the element is still only 79px tall.

**Comment by ngduser** [comment]
Thanks for the response.

It doesn't look like either of those issues apply here, the image is entirely onscreen and the full size shows up and is added to html2canvas, as shown in the log above.

This is the image- 

![image](https://cloud.githubusercontent.com/assets/5769132/26016211/bc72e45c-3729-11e7-8957-750d884700a1.png)

And after html2canvas crops it- 

![example](https://cloud.githubusercontent.com/assets/5769132/26016407/7975b778-372a-11e7-8b6b-c041773363c4.png)
.

There is no single element or group which makes up the output I receive, it is strange.

**Comment by eKoopmans** [comment]
From the logs you posted:

* line 2: initial canvas size is 1920 x 653 (screen/window size)
* line 15: `top: 574` means that the top of your root element is at 574px (using `getBoundingClientRect()`)
* 653 - 574 = 79px, the height you're receiving
* all signs point to this being an "offscreen rendering" problem - if your window is 653px tall and the start of your element is at 574px, then most of your element is offscreen

Again, I recommend trying [this build](https://github.com/eKoopmans/html2canvas/tree/develop/dist) and see if it fixes your problem. Otherwise it would help if you could post a [jsFiddle](https://jsfiddle.net/69kc2t2y/) illustrating the issue.

**Comment by eggers** [comment]
@eKoopmans I was having a similar issue, that build fixed the issue. Thanks.
