### ISSUE TITLE
"Tainted canvases may not be exported" after moving static resources to CDN.

### ISSUE THREAD

**Issue by vishva-villvay** [niklasvh/html2canvas#1130]
Thank you very much for your wonderful JS library. It was working perfectly until recently we moved some static resources to be delivered from a CDN.

It is actually a Google cloud storage bucket. We are delivering all JavaScript, CSS and images/icons for our web application hosted at Google AppEngine from a Cloud storage bucket.

The error we are getting is "Uncaught (in promise) DOMException: Failed to execute 'toDataURL' on 'HTMLCanvasElement': Tainted canvases may not be exported."

I tried moving the related JS files to be delivered from the same domain (not CDN), but this error was still there.

Is there any workaround for this, or do we have to take the step back from Cloud Storage for this to work..

Here is the URL on GCS from where the library is delivered from:
https://storage.googleapis.com/proapp_static/js/html2canvas.js
https://storage.googleapis.com/proapp_static/js/html2canvas.svg.js

**Comment by eKoopmans** [comment]
Hi @vishva-villvay, the problem is with [cross-domain images](https://developer.mozilla.org/en-US/docs/Web/HTML/CORS_enabled_image). For security reasons, trying to use an image from a different domain in a canvas causes problems (i.e. a tainted canvas). There are two html2canvas [options](https://html2canvas.hertzen.com/documentation.html#available-options), `useCORS` and `proxy`, which are designed to try to get around that problem. They're not perfect solutions though - you can read more over at #951 and #592.
