### ISSUE TITLE
css Mask image/-webkit-mask-image support

### ISSUE THREAD

**Issue by celik75** [niklasvh/html2canvas#1133]
When will this be available?

**Comment by niklasvh** [comment]
Currently no plans to support image masks.

**Comment by salis77** [comment]
I need to use mask-image too,**please** do something! 
thanks!

**Comment by salis77** [comment]
@niklasvh  is it possible to help me with [this issue](https://stackoverflow.com/questions/51906200/real-time-web-page-screenshot-using-phantomjs) which is related to **mask-image** and of course **html2canvas**?!
I'll be so thankful to you if you could guide me just this time! I'm really Anxious and upset due to this problem!

Impatiently waiting for your help. Dear friend

**Comment by ravichauhan** [comment]
Any alternative solution availble ?

**Comment by Be1zebub** [comment]
pls 🙏

**Comment by liel-HB** [comment]
Still no solution for that? :(

**Comment by maigan22** [comment]
pls so

**Comment by finebo** [comment]
still no support

**Comment by eeeemune** [comment]
still not...😥
