### ISSUE TITLE
proxy not working and having issue loading cross domain images

### ISSUE THREAD

**Issue by NikhilRadadiya** [niklasvh/html2canvas#1171]
I'm trying to generate pdf with dynamic images from other server. and I know the domain name only.

I've tried to use proxy like this,
```
"proxy": "http://abc.xyz.com",
"useCORS": true,
```

but it's not working
Also, there are ` No 'Access-Control-Allow-Origin' header is present on the requested resource` also,
Also tried to check some of the answers but no luck there.
Please help me with these issues

**Comment by lverledens** [comment]
I had the same issue and I found this beautiful solution:

Short version: download the images to the local storage of the browser and change the src of all images to use the data stored in your local storage instead of a url pointing to a different server.
Long version: http://ttola.com/avoiding-cors-issues-on-using-html2canvas-with-images/

**Comment by NikhilRadadiya** [comment]
@lverledens where to add the code from that link, for converting src to dataURL?
