### ISSUE TITLE
nodejs backend-end support.

### ISSUE THREAD

**Issue by NStal** [niklasvh/html2canvas#121]
Nodejs already support some DOM/canvas simulation. I found this feature very useful and interesting to rendering some images with text using html/css at backend .Will nodejs backend support be considered in future release ?

**Comment by JohnDMathis** [comment]
@niklasvh It's been over 7 years since this issue was closed. Do you think it's possible that node now has better support for things like `getBoundingClientRect` that might make it worth revisiting this issue? I'd like to be able to render a react component on the server and generate a jpg, on demand. (We are building an integration with something that will display text and images, but not html.) Phantomjs may be the next best option, but I'd rather render something to the canvas and output that as an image, than to rely on browser and screenshots. Thanks in advance for your time.

**Comment by niklasvh** [comment]
I would highly recommend using a real browser if you intend to be rendering something on the server. Additionally, I don't think there are any node libraries that would do full layout similarly to that of `getBoundingClientRect`
