### ISSUE TITLE
Unable to use html2canvas function along with requirejs, html2pdf in Beta release

### ISSUE THREAD

**Issue by svankamamidi** [niklasvh/html2canvas#1235]
Unable to use html2canvas function along with requirejs, html2pdf. I get error 'Uncaught (in promise) ReferenceError: html2canvas is not defined'

I get this error in Beta releases where as working fine in Alpha release.

**Comment by CelesterSpencer** [comment]
You need to provide a polyfill since not all browsers support Promises yet. Something like this [ES6 Promise](https://cdnjs.cloudflare.com/ajax/libs/es6-promise/4.1.1/es6-promise.auto.min.js). Also i had an issue that html2canvas didn't drew any svgs in IE. You need to make sure that you require html2canvas as well as html2canvas.svg and i had to make sure that html2canvas.svg got inserted in html2canvas which can be seen in the first few line in the code below.

```js
define(['html2canvas', 'html2canvas.svg'], function(html2canvas, html2canvasSvg) {
    html2canvas.svg = html2canvasSvg;
    window.html2canvas = { svg: html2canvas.svg };

   // actual drawing logic goes here
});
```

Hope this is helping you.
