### ISSUE TITLE
There are some defects when page have highchart's charts.

### ISSUE THREAD

**Issue by xiaozhu39505** [niklasvh/html2canvas#1277]
I used the highchart plugin, please see below:
![defect2](https://user-images.githubusercontent.com/10821897/33204826-ba18efca-d13f-11e7-896b-c7c0d7ff3b11.jpg)
![defect1](https://user-images.githubusercontent.com/10821897/33204829-ba654b40-d13f-11e7-93f1-6e9561d5fca9.jpg)

**Comment by florianleroy** [comment]
Hey,

This specially appends on svg text nodes.
It's been a while since the first open issue concerning that bug, and many issues are talking about it.
Despite the fact they're some work-around, nothing has bring a reliable solution.

See: [#541 #616](https://github.com/niklasvh/html2canvas/pull/616/commits/79f50bb3c0992aa1fd52a26e72d13010c515cb90)
So this fix doesn't duplicate the svg text rendering, but it doesn't respect the style applied to it anymore.

**Comment by xiaozhu39505** [comment]
Thanks. I have resolved it. The solution is in: [https://stackoverflow.com/questions/34042440/using-html2canvas-to-render-a-highcharts-chart-to-pdf-doesnt-work-on-ie-and-fir](url)
