### ISSUE TITLE
background color has no effect if canvas object's height is smaller

### ISSUE THREAD

**Issue by eldyvoon** [niklasvh/html2canvas#1283]
I set the width and height according to my content's size, but how can I fill the blank area below.

https://i.imgur.com/V5aYreR.png

Not sure why the background param has no effect, `bgColor` is set to '#eeeeee' but I see white color?

my full code as below:

```
import $ from 'jquery'
import jsPDF from 'jspdf'
import canvg from 'canvg-browser'
import html2canvas from 'html2canvas-render-offscreen'

const captureAndDownload = (width, height, delayMs, DOMNode, fileType, fileName, bgColor) => {

		//jspdf requires html2canvas to be attached to the window scope
		window.html2canvas = html2canvas

		$(window).scrollTop(0)

		setTimeout(function(){

			//replace all svgs with a temp canvas
			const replaceSVGwithCanvas = function(callback) {
			  	//find all svg elements in $container
			  	const $container = $('#' + DOMNode);
			  	//$container is the jQuery object of the div that you need to convert to image. This div may contain highcharts along with other child divs, etc
			  	const svgElements = $container.find('svg');
			  	svgElements.each(function() {
				  	let canvas, xml;
				  	canvas = document.createElement("canvas");
				  	canvas.className = "screenShotTempCanvas";
				    //convert SVG into a XML string
				    xml = (new XMLSerializer()).serializeToString(this);
				    // Removing the name space as IE throws an error
				    xml = xml.replace(/xmlns=\"http:\/\/www\.w3\.org\/2000\/svg\"/, '');
				    //draw the SVG onto a canvas
				    canvg(canvas, xml);
				    $(canvas).insertAfter(this);
				    $(this).hide();
				});
			  callback(); //to be called after the process in finished
			};

			replaceSVGwithCanvas(function() {
				html2canvas(document.getElementById(DOMNode), {
					background: bgColor,
					onrendered: function(canvasObj) {

						const pdf = new jsPDF('p', 'mm', [width, height])
						const pdfConf = {
							pagesplit: false,
							background: bgColor
						};

				    	document.body.appendChild(canvasObj); //add page in pdf
				    	pdf.addHTML(canvasObj, 0, 0, pdfConf, function() {
				    		document.body.removeChild(canvasObj);
				    		pdf.save(fileName + '.' + fileType);

				    		window.location.reload();
				    	});
					}
				});
			});

		}, delayMs)
}

export default captureAndDownload
```

**Comment by niklasvh** [comment]
Is this still an issue with [v1.0.0](https://github.com/niklasvh/html2canvas/releases)? If so, could you please share an example on [jsfiddle](http://jsfiddle.net/az5j0766/).

**Comment by geoffrey-eisenbarth** [comment]
@niklasvh  Not sure if it's helpful, but I had a similar image with all 1.0.0-rcs (1-5). I tried to replicate it in [this jsfiddle](https://jsfiddle.net/ojuL80sn/1/), without much luck. The issue I was having in my original code was that the background color of the `progress-bar`s weren't rendering properly in image files (they were very, very light, looked like a white background with sparse, tiny colored dots instead of a full background).

However, I did find out that in my personal code (again, couldn't replicate this in the jsfiddle) that if I changed their height from `2em` to `25px` the issue was solved, so perhaps there's something related to how html2canvas deals with background colors and height units?

Apologies for not being more helpful. The problem seems fixed for me as long as I use `px`, but I figured I'd post this here for any future people stumbling across a similar issue.
