### ISSUE TITLE
white stripe on the left side of the canvas

### ISSUE THREAD

**Issue by MessmerSeverin** [niklasvh/html2canvas#1467]
when i create the canvas i get an empty white stripe on the left site. theres no css there like padding and it worked with version 0.41

**Comment by roostiq** [comment]
having same issue right now

**Comment by roostiq** [comment]
@MessmerSeverin i found workaround for this issue, but it works only if you don't need to show div that you converting to canvas. It was my case, because i am generating images to share in FB, so i made wrapper with following CSS

```
.capture-wrapper {
    position: fixed;
    left: 0;
    top: 0;
    width: 1200px;
    height: 630px;
    pointer-events: none;
    opacity: 0;
}
```

and white stripe doesn't appear in canvas. Kind if ugly solution, but worked in my case.

**Comment by MessmerSeverin** [comment]
my image is white and nothing else if i do this

**Comment by roostiq** [comment]
@MessmerSeverin do you try to capture wrapper or div placed inside of wrapper? Because when trying to capture wrapper, converter will read opacity: 0. Probably, that's why your result is plain white. You should place your source div inside of wrapper. Sorry, i didn't describe my solution well enough first time. Let me know if it will work for you

**Comment by niklasvh** [comment]
Fixed in https://github.com/niklasvh/html2canvas/commit/a3e25d71cb39eb295fc9bee94712be03a6e71204
