### ISSUE TITLE
Svg styles not on being applied on Safari

### ISSUE THREAD

**Issue by budaaaa** [niklasvh/html2canvas#2476]
### Specifications:

 * html2canvas version tested with: ^1.0.0-rc.7
 * Browser & version: Safari 14.0.1
 * Operating system: Big Sur

I have an SVG that I want to convert as a png file through html2canvas and then download it. I tested it on Chrome, Firefox, and Opera, and it works perfectly. 

However, on Safari, the styles are not applied, returning me a black rectangle.

Here's a simplified version of what I'm trying to do. 

https://jsfiddle.net/oum4hsfk/

**Comment by iamkratos** [comment]
@budaaaa did you ever figure this out? I'm having the same issue

**Comment by budaaaa** [comment]
@iamkratos Hello, nope we decided to move the implementation to the backend.

**Comment by ybaturin** [comment]
@iamkratos @balupton 
looks like the reason is the same as in https://github.com/niklasvh/html2canvas/issues/2495
The library copies all computed style and pasts it inside "style" for every SVG node.
And somehow, it breaks Safari engine and influence on the result picture.

Here https://jsfiddle.net/yaznayka/rep3bwnh/1/ I copied your example and made only single change to prevent copy style behavior https://i.imgur.com/6BOXu45.png, and now all works properly in Safari

**Comment by amok** [comment]
Monkey patch for those who're awaiting for #2497 to get merged

```js
function monkeyPatch(svgElement) {
      const cloneNode = Node.prototype.cloneNode;
      Node.prototype.cloneNode = function () {
        const item = cloneNode.apply(this, arguments);
        if (svgElement.contains(this)) {
          item.style.setProperty = () => {};
        }
        return item;
      }
  return function monkeyPatchRestore() {
   Node.prototype.cloneNode = cloneNode; 
  }
}
```

usage:

```js
const restore = monkeyPatch(document.querySelector('svg'))
html2canvas(...)
restore();
```
