### ISSUE TITLE
M1 apple with Error: RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by Danielguang** [niklasvh/html2canvas#2539]
Please make sure you are testing with the latest [release of html2canvas](https://github.com/niklasvh/html2canvas/releases). 
Old versions are not supported and issues reported for them will be closed.

# Please follow the general troubleshooting steps first:

- You are using the latest [version](https://github.com/niklasvh/html2canvas/releases)
- [You are testing using the non-minified version of html2canvas and checked any potential issues reported in the console

### Bug reports:
I run with html2Canvas in mac M1。 I try to capture screen with base 64 image, the image size is quite large,  like more than 1M, the console output

![image](https://user-images.githubusercontent.com/10718395/119466610-60ef8580-bd77-11eb-8126-5717be643d19.png)

### Specifications:

 * html2canvas version tested with: "version": "1.0.0-rc.7"
 * Browser & version:the latest chrome
 * Operating system:MacBook Pro (13-inch, M1, 2020), Mac OS Big Sur

**Comment by cdub32k** [comment]
I figured out the cause of this error. In /src/css/syntax/tokenizer.ts, the constant `SLICE_STACK_SIZE` is too large and causes a stack overflow in the Mac M1 version of Chrome. I changed it to 30000 and no longer had the stack overflow. It was being caused by having a large base64 encoded image in the HTML being converted to a canvas.

Please fix this ASAP. Currently in my project I had to stop including html2canvas in my package.json, and I made a custom build that I include separately. Please update `SLICE_STACK_SIZE` to avoid the stack overflow in Mac M1 Chrome.

```
private consumeStringSlice(count: number): string {
        //The below variable causes a stack overflow in Chrome on Macs with M1 chip
        const SLICE_STACK_SIZE = 60000;
        let value = '';
        while (count > 0) {
            const amount = Math.min(SLICE_STACK_SIZE, count);
            value += fromCodePoint(...this._value.splice(0, amount));
            count -= amount;
        }
        this._value.shift();

        return value;
    }
```

**Comment by niklasvh** [comment]
I am unable to repro [this ](https://jsfiddle.net/rxot7g9f/) on M1 Chrome

**Comment by cdub32k** [comment]
@niklasvh It is most definitely happening on the M1 version of Chrome with the latest version of html2canvas.

**Comment by cdub32k** [comment]
@niklasvh  It has to do with the number of arguments a function can take. No problem on Firefox, Safari on the Mac M1. But Chrome on M1 gets a stack overflow if you try to pass 60,000 arguments to a function. I only prevented the stack overflow when I changed `SLICE_STACK_SIZE` to be 30000 instead of 60000. It occurs when there is a large base64-encoded image in what you are trying to convert to a canvas. This is absolutely 100% happening, so please address.

**Comment by niklasvh** [comment]
You can downvote all you want, but unless there is a clear way to repro this, just changing it from 60,000 to 30,000 will in no way ensure that it fixes it overall and not just for you, that it remains working in the future, or that 30,000 is in fact the value it should be, vs for example 40,000 or 20,000.

**Comment by cdub32k** [comment]
I am not proposing a fix, but I know the source of the error, it is `SLICE_STACK_SIZE` being too large, cannot pass that many arguments to a function in M1 Chrome.

Surprisingly, it is only M1 Chrome. All other versions of Chrome do not have the error. Maybe Google will fix it, because I would imagine they would increase not decrease the stack size for M1 version of Chrome.

I can continue to create a custom build and change `SLICE_STACK_SIZE` to 30000 for my project only. However, this will obviously make updates and maintenance more difficult. So please look into this, or at least keep it on your radar, to resolve ASAP.

Thank you, love the package

**Comment by DMQ** [comment]
I also encountered this problem!

**Comment by hansGerdClassen** [comment]
same error here ... 
mac os 12.0.1, Apple M1
Chrome Version 96.0.4664.110
html2canvas 1.3.3

**Comment by DMQ** [comment]
来信已收到！！谢谢！！！

**Comment by shanxilipu** [comment]
I also encountered this problem!
mac os 12.0.1, Apple M1 PRP
