### ISSUE TITLE
Image not showing for CORS

### ISSUE THREAD

**Issue by elifsz** [niklasvh/html2canvas#2548]
I can't load the image from the CORS. I added a proxy according to the tutorials in my own code, but it didn't help. I am using Angular.
**Example** : http://jsfiddle.net/3kyrtp6d/2/

**Comment by niklasvh** [comment]
Can you please try reproducing this with 1.0.0? 0.4.1 is from ~8 years ago, and the library has gone through a few rewrites since then. Even if there was a bug in that version for CORS, it wouldn't be receiving any fixes. If you can still reproduce the issue with 1.0.0, feel free to open another ticket.
