### ISSUE TITLE
Empty canvas returned for Safar 7 on Mac OS X 10.9

### ISSUE THREAD

**Issue by xinli2k5** [niklasvh/html2canvas#293]
Example is here

http://jsfiddle.net/rR9Rs/4/

Chrome showed the expected results but Safari gave nothing.

**Comment by lcw0622** [comment]
I meet this problem too, and I solved this problem by assign option `height` .
It seems something wrong when html2canvs calculating DOM position, if you can give element height directly, then maybe avoid such calculating by html2canvas itself, and now it just calculate some offset so that you can get a correct canvas.
