### ISSUE TITLE
Graffiti Font not working while converting to image

### ISSUE THREAD

**Issue by arpitsunny** [niklasvh/html2canvas#328]
Hello Friend, i've came through one more problem which is only occurring with IE 11. PFA screenshot which depicts same. Page consists of all graffiti font and gets ignored while conversion. Can you please guide any way out?

**Comment by diego-rey** [comment]
Hi all, I'm having a similar problem to this one. I created a widget that uses html2canvas to take a screenshot. The problem is that the widget must be inserted in a site inside an iframe, the capture works but the fonts don't load. Here is a simple example of what happens: [test-case-iframe](http://www.mediafire.com/file/8qzxzy8qv9jovmd/test-case-iframe.zip/file )
