### ISSUE TITLE
Cross Origin Image does not load in IE9 but works on Chrome (fiddle provided)

### ISSUE THREAD

**Issue by samsonkhisty** [niklasvh/html2canvas#416]
http://jsfiddle.net/fuggfuggfugg/jLLut/4/  This fiddle works on Chrome but not on IE9, The image basically does not get drawn. The logging error is as follows: "Error loading <img>: cross_origin_image" 

Any pointers are deeply appreciated. 

edit: updated fiddle http://jsfiddle.net/fuggfuggfugg/jLLut/7/

**Comment by usmonster** [comment]
Can this be logged and/or added to the readme?

**Comment by usmonster** [comment]
> IE9 has limited CORS support through XDomainRequest, but it only supports plaintext data, so you cannot use it to load images.

Actually, I just tested this on IE9 and found it to not be true (anymore?). Seems this may have been patched within the past ~4 years; according to [a Microsoft blog](http://blogs.msdn.com/b/ieinternals/archive/2010/05/13/xdomainrequest-restrictions-limitations-and-workarounds.aspx):

> Note: As of 2014, XDomainRequest doesn't appear to send any Content-Type header at all. It's not clear to me when this changed.

Which means the content type of the returned resource can be anything, including image.

And so it could be worth it to reopen this issue and try using `XDomainRequest` (if available) when we find that XHR doesn't support CORS.

Thoughts?

(Another, related optimization for image loading should be to allow both the `proxy` and `useCORS` options to be specified in the same invocation, with the behavior in that case being "attempt CORS, and if that fails, fall back to the proxy." The current logic ignores the proxy if `useCORS` is `true`.)

**Comment by usmonster** [comment]
@niklasvh Can we reopen this, since IE9 is a supported browser and a workaround seems possible?

**Comment by niklasvh** [comment]
If CORS requests aren't supported, it should fallback to jsonp, so it should work regardless, or am I missing something here?

**Comment by usmonster** [comment]
I think the fallback only works in the case of anonymous CORS, but I need to simplify my test case to make sure--I'll let you know.

That said, upon further investigation, there would actually seem to be little to no advantage to using `XDomainRequest` in the end, since it doesn't support credentials and is likely no better than the JSONP fallback.

(Unrelated, there seems to be dead code here: https://github.com/niklasvh/html2canvas/blob/master/src/proxyimagecontainer.js#L2)

**Comment by niklasvh** [comment]
Removed the dead code. jshint should be configured with `unused: true`, but will need #502 for that.

**Comment by usmonster** [comment]
Yep, the best workaround I could find is exactly what @tejacques said: 

> By far the easiest thing to do for CORS images in IE9 is to proxy them through your domain to avoid CORs altogether.

À la this:

```js
var opts = { ... };

if ('withCredentials' in new XMLHttpRequest()) {
        opts.useCORS = true;
} else {
        opts.proxy = 'http://myproxy.example.com/proxy';
}

html2canvas( ... , opts).then( ... );
```

I think this and similar cases could be handled automatically by html2canvas if both CORS and a proxy could be specified in the options at the same time, using the proxy only as a fallback in such cases (as described at the end of [a previous comment](#issuecomment-69938064)). If a proxy isn't given, the JSONP fallback can be tried.

Thoughts? If this sounds like a good idea, I can open a new issue.

**Comment by samsonkhisty** [comment]
Apologies for my stupidity, but I have no clue whatsoever about proxies and how to implement one. Especially with a Ruby on Rails App. 

Where can I find more on this? 

Thanks in advance.

**Comment by usmonster** [comment]
It's not stupidity, it's just not yet learned. :]

In general, a proxy is a service running on one server that allows you to access resources that live on other servers. In html2canvas, a proxy would be used to load cross-origin images via javascript. This helps circumvent browser restrictions, namely the Same Origin Policy, because the proxy is (presumably) on your own domain, so the browser is just getting some "local" image.

For hints on implementing one, you can check out, for example, http://apidock.com/ruby/Net/HTTP. You can essentially write a controller that listens for a request with a "url" parameter, fetches the URL, and returns the content. (Note that html2canvas will only use the proxy for images.)

See some sample implementations in other languages here:
https://github.com/niklasvh/html2canvas-proxy (Python)
https://github.com/brcontainer/html2canvas-php-proxy (PHP)

Hope that helps, and feel free to open-source your result!

**Comment by samsonkhisty** [comment]
@usmonster Thank you. Much appreciated. I will take a shot at this in sometime.

**Comment by rajvijariwala** [comment]
I am having 'SecurityError' in IE11. In chrome it works fine with useCORS setting. The version of html2Canvas I am using is  * html2canvas 1.0.0-alpha.11"

Below is my code. Please help @samsonkhisty  @niklasvh @usmonster 
The service we are getting images are set CORS. What I am missing?

`html2canvas(sourceChart, {
'width': sourceChart.clientWidth,
'height': sourceChart.clientHeight,
'proxy': url,
'onclone': function (cloneDoc) {
$(cloneDoc).find('.canvasContainer').css('overflow', 'visible')
	.find('.orgchart:not(".hidden"):first').css('transform', '');
	
},
'onrendered': function (canvas) {
	var doc = {};
	var docWidth = Math.floor(canvas.width * 0.2646);
	var docHeight = Math.floor(canvas.height * 0.2646);
	if (docWidth > docHeight) {
	doc = new jsPDF('l', 'mm', [docWidth, docHeight]);
	} else {
	doc = new jsPDF('p', 'mm', [docHeight, docWidth]);
	}
	doc.addImage(canvas.toDataURL(), 'png', 0, 0);
	doc.save('OrgChart' + '.pdf');
}
});`
