### ISSUE TITLE
Not rendering shadow dom elements

### ISSUE THREAD

**Issue by fernandezpaco** [niklasvh/html2canvas#430]
I am working on a new project using polymer webcomponents.

The problem is that html2canvas is not rendering the shadow dom

Can you please tell me where should i work on your library in order to have support for webcomponents?

**Comment by rcocetta** [comment]
@niklasvh Did somebody fix this issue. I'd be interested in using the library, but I'm using Polymer and ShadowDOM and it's not working for me.

**Comment by mkhatib** [comment]
Unfortunately this also fails because of the way html2canvas tag the node to be rendered and then clone the entire document and inability to pierce shadow-dom using `querySelector`. 

Even when tagging the node up to the document root the tagging seems to be lost after the first shadow dom during the cloning. Not sure what's happening there.

**Comment by srajabhoj** [comment]
@niklasvh can you share a link (https://github.com/niklasvh/html2canvas/blob/master/src/nodeparser.js) again, it shows 404.

**Comment by tmatetwar** [comment]
@niklasvh : We are facing the same issue (unable to render SHADOW-DOM), let us know if anyone had worked on it.

**Comment by val1984** [comment]
@srajabhoj Following version 1.0.0 rewrite, it's probably https://github.com/niklasvh/html2canvas/blob/master/src/NodeParser.js

**Comment by Jeffen** [comment]
My workaround is to clone the content and css that as you want to render a HTMLElement , then append it to `document.body`. Set style `filter:opacity(0)` because html2canvas does not support this but supported in modern browser. Remove it after render.

However, it is very hard to do if you included many shadow-dom element in the content you want to render. Still have no idea on that.

Here is my code in Angular
```typescript
const newRef = this.renderRef.nativeElement.cloneNode(true);
this.renderer.setStyle(newRef, 'filter', 'opacity(0)');
this.renderer.appendChild(document.body, newRef);
html2canvas(newRef).then(canvas => {
     if (canvas.toBlob) {
          canvas.toBlob(
            blob => {
              fileSaver.saveAs(blob, 'image.jpg');
              this.renderer.removeChild(document.body, newRef);
              alert('Image has been downloaded to your device');
            },
            'image/jpg',
            0.8
          );
     }
});
```

**Comment by rocco** [comment]
@Jeffen this was very helpful, thank you! Also the file saver thing was of great help. Just in case anyone wonders how this works, I did it like this:

`$ npm i file-saver`

`import * as saveAs from 'file-saver';`

`saveAs(blob, 'image.jpg');`

**Comment by lf-achyutpkl** [comment]
Is there any update on this issue? 
Or any workaround for the app having nested shadow dom?

**Comment by trusktr** [comment]
The `html2canvas` lib would need to be updated so that it can traverse the "composed" tree instead of the "light tree".

If all ShadowRoots have `mode:'open'`, this should be fairly straight forward.

If we want to support ShadowRoots with `mode: 'closed'`, then this will be more complicated and will require patching of `attachShadow` in order to track references to shadow roots so that we can traverse on them.

Once we know how to traverse the the "composed tree" in general, then we'd need to update `html2canvas`'s recursive `DocumentCloner.cloneNode` method to have it traverse the composed tree instead of the light tree.

**Comment by TremayneChrist** [comment]
Slotted content could be trickier to handle. You'd need to find the corresponding slots in order to render the content into the correct place.

```html
<!--my-component-->
<div><slot name="some-region"></slot></div>
<slot></slot>
```
```html
<!--my-app-->
<my-component>
  Default Slotted Content
  <button slot="some-region">Button</button>
</my-component>
```

**Comment by conceptree** [comment]
Hi, did anyone reached a solution for this shadow dom problem?

**Comment by trusktr** [comment]
I don't think anyone has tried to implement this yet.

Basic steps:

- Monkey patch `Element.prototype.attachShadow` so that the lib can have access to all roots, even if they are `closed`.
- For each root that is ever created with `attachShadow` (in the future we would need to consider [Declarative Shadow DOM](https://github.com/WICG/webcomponents/issues/914) but it may be impossible to track those)
  - Track which roots belong to which nodes (f.e. with a `WeakMap`).

When traversing later, children of an element with a shadow root will be skipped if an element is seen to have a root (detected with the `WeakMap`, even a closed one root), and instead traversal will go into the shadow root and into the `assignedNodes` of any encountered `<slot>` elements, and continue like so all the way down all shadow roots.

I'm not familiar with the html2canvas impl, but if needed, functions like `querySelector` could be monkey patched to traverse the composed tree instead of only the local tree of the node on which it is called (make it "piercing").

**Comment by trusktr** [comment]
I went ahead and made composed tree traversal example, in case it helps someone eventually:

https://codepen.io/trusktr/pen/0d5b3731fcb2ebe54f99316bfb55b117

The output shows the nodes of the composed tree in depth-first preorder (verify by inspecting the elements).

If there are any parts of `html2canvas` that rely on traversing the DOM tree, it may need to be replaced with something like that.
