### ISSUE TITLE
0.5.0-alpha not working in a Firefox extension

### ISSUE THREAD

**Issue by jmrodriguez** [niklasvh/html2canvas#442]
I'm using the library as part of a Firefox extension (implemented using the addon-sdk), as part of a content script.

here's the content script definition:

// Create a page mod (in file main.js)
var pageMod = pageMod.PageMod({
  include : "*",
  contentScriptFile: [data.url("jquery-2.1.0.min.js"),
                      data.url("html2canvas.min.js"),
                      data.url("contentScript.js")],
  onAttach: startListening
});

this is the relevant part in contentScript.js

console.log("start");
var data = {};
html2canvas($("body"), {
onrendered: function(canvas) {
   console.log("here2");
   // canvas is the final rendered <canvas> element
  data.image = canvas.toDataURL("image/png");
   console.log(data.image);
   console.log("here3");
   window.open(data.image);
   console.log("here4");
   self.port.emit("processImage", JSON.stringify(data));
   console.log("here5");
});
console.log("end");

Only the "start" and "end" console.log messages are displayed using 0.5.1, like the html2canvas section is never executed.

Using 0.4.1 all the console.log messages are displayed

There are no further errors in the console or anywhere else

**Comment by Jnull** [comment]
Yep, 
So I'm experiencing this as well, now that Firefox has depreciated cfx sdk in light of the new jpm sdk (nodejs), things have since become a little bit easier to test with jpm. It may however be more complex with more combinations to try though.

After all my testing, the only thing that works for me is v4.0 as aeropostDevelopment suggested.

I've tried all these in combination:  
cfx
jpm
html2canvas (no promise callback format)
html2canvas (promise callback format)
version5.0.1-alpha
version5.0.2.alpha
window.settimeout (i couldn't get this to work even with the example)

Anyhow, i've created two Firefox add-on examples, 4.0 works - 5.0 does not. 

https://github.com/Jnull/html2canvas_4.0_ff_addon
https://github.com/Jnull/html2canvas_5.0-alpha.2_ff_addon

all thats needed is 'npm install jpm' && jpm run (with-in the root of the folder)
