### ISSUE TITLE
html2canvas google map capture not working on chrome 

### ISSUE THREAD

**Issue by bayramucuncu** [niklasvh/html2canvas#524]
http://jsfiddle.net/barteloma/nqqh9w3q/4/

I want to capture google map. The script is working fine on Mozilla Firefox and IE. But the tiles are missing after drag map.

**Comment by freestyle21** [comment]
I have the same question even if use the proxy.

**Comment by brcontainer** [comment]
Duplicate from:
-------------------
- https://github.com/niklasvh/html2canvas/issues/485
- https://github.com/niklasvh/html2canvas/issues/462
- https://github.com/niklasvh/html2canvas/issues/244
- https://github.com/niklasvh/html2canvas/issues/345
- https://github.com/niklasvh/html2canvas/issues/453

**Comment by manueltimita** [comment]
Regarding some of the issues reported above, I suspect it's not about `html2canvas` itself.

Missing markers - not sure about the cause, but if one puts a Base64 string (e.g. `'data:image/png;base64,...'`) instead of an image URL as the `icon` property in `new google.maps.Marker()`, the resulting canvas shows the marker as expected. Not a significant performance issue if you plan to have no more than a couple of hundred markers on the map.

As about the missing tiles after dragging, it is clearly caused by not running `html2canvas(document.getElementById("map-canvas"),{...})` in a `tilesloaded` / `bounds_changed` event, or similar. As expected, the content of element `"map-canvas"` changes whilst interacting with the map.

Great work, BTW.
