### ISSUE TITLE
Some SVG elements misplaced when using Internet Explorer

### ISSUE THREAD

**Issue by spandel** [niklasvh/html2canvas#525]
In this example, lines are misplaced by half their stroke-width, both horizontally and vertically: [jsFiddle](http://jsfiddle.net/bv16o50f/1/).
Using Internet Explorer 11. No problems in Chrome.

**Comment by wbarrantes** [comment]
Hmm, I have a similar issue on **IE11** (no problems in Chrome or FF).
I'm using MathJax to display MathML content. The content is on a 'span', then I convert the html element to canvas (using html2canvas v.0.4.1). The problem is on IE11 the mathML content is cut off and misplaced.

Please help.
Thanks!

**Comment by zky829** [comment]
+1
