### ISSUE TITLE
Background Color or Image take full rectangle, not inline

### ISSUE THREAD

**Issue by donohoe** [niklasvh/html2canvas#548]
I have multiple span tags in a paragraph.

When I have one of those span tags with a background-color or background-image it will treat it will encompass areas outside of the SPAN and give an entire rectangle that background.

This is an example of two SPAN tags with different background colors. The top part of the image represents the result from html2canvas, while the lower part of this image shows the DOM view:

![image](https://cloud.githubusercontent.com/assets/36363/6559219/aaf68c32-c657-11e4-9d66-57b42f9f627a.png)

Any way to avoid this?

Again, using a background-color or background-image have the same result.

Using Chrome Version 41.0.2272.64 beta (64-bit) on OSX.

**Comment by claudiomedina** [comment]
Any solution on this?

**Comment by niklasvh** [comment]
Is this still an issue with [v1.0.0](https://github.com/niklasvh/html2canvas/releases)? If so, could you please share an example on [jsfiddle](http://jsfiddle.net/az5j0766/).

**Comment by FTOH** [comment]
@niklasvh Yes.
http://jsfiddle.net/az5j0766/336/

**Comment by volser** [comment]
Any solution?

**Comment by fellnerse** [comment]
Looking forward for a fix 🥳

**Comment by johnozbay** [comment]
@niklasvh this is still a problem in 1.3.2, and you can see it here : 
http://jsfiddle.net/n6oyz1r0/12/

^ It's an updated version (using v1.3.2) of the minimum reproducible example @FTOH posted here. 

Discovered this while using [html2pdf](https://github.com/eKoopmans/html2pdf.js) and perhaps @eKoopmans could bring more examples as well. 

Here's all the issues I found that seems to be related to this problem :
https://github.com/niklasvh/html2canvas/issues/2447
https://github.com/niklasvh/html2canvas/issues/1497
https://github.com/niklasvh/html2canvas/issues/1742

--

And here's an example from html2pdf, that I think is related to this issue : 
https://github.com/eKoopmans/html2pdf.js/issues/280

--

If you can point me the right direction, I'd be happy to work on a solution full time and file a PR for this.

Many thanks for all the great work you've been putting out, 
Best,
J

**Comment by johnozbay** [comment]
An interesting discovery : 
http://jsfiddle.net/bakg3sz6/

Looks like this is somehow about the order of rendering / drawing the background-color. I changed the background color to a semi-transparent one, and now it's possible to see the text through the background, confirming that the background color is somehow drawn over the text :

![Screenshot 2021-09-10 at 12 03 51](https://user-images.githubusercontent.com/611338/132829430-ed9b4fc2-cf97-4d68-9acc-473b26b6ce38.png)

I'm guessing this is happening because even the inspector/browser itself highlights this span element as full width : 

![Screenshot 2021-09-10 at 12 06 28](https://user-images.githubusercontent.com/611338/132829966-406ce4a5-7a63-4e85-a956-7a1616bd63d9.png)

So when html2canvas tries to read the element's width/height, understandably it reads the width & height of the whole box for the element, and draws the background color for the whole area in full. 

Discovering this, I'm no longer entirely sure if there's a solution to this problem.
Off the top of my head, a duct-tape horrible fix is to iterate elements in reverse order so that text is drawn over the background first. OR to read the parent's background color (i.e. white) and draw the following elements with white background, but I'm guessing both of these would require significant changes to the library.

**Comment by eKoopmans** [comment]
☝️ Hey I don't have too much context for this, but it looks like (from your first fiddle) adding the `foreignObjectRendering: true` option to html2canvas resolves the issue?

**Comment by johnozbay** [comment]
Hey there @eKoopmans! Thanks for the ping! 

In the reproducible example `foreignObjectRendering` does solve the problem, however with `foreignObjectRendering` enabled, `html2pdf` seemed to generate blank PDF pages in our implementation. And when disabled – the issue above seemed to happen. 

The band-aid solution we came up with for this problem is to split sentences with background-color into separate words (incl spaces),  put each word into a new `span`, and style `span` elements individually with `background-color`, right before exporting the canvas to PDF.

This way, for our use case, none of the words/spans are multiple-lines long, and background colors don't overlap / cover other elements. It's a hacky workaround, but seems to be efficient enough for our use case, and hopefully would save someone else another minute or two of head scratching. 😅

**Comment by faressoft** [comment]
Workaround:

```javascript
// Workaround for html2canvas multi-line highlight issue:
// Split highlighted spans into individual word spans to prevent background-color
// from covering the whole bounding box instead of just the text
const highlights = element.querySelectorAll('.highlighted');
const originalHighlights = [];
highlights.forEach((span) => {
  const classes = span.className;
  const originalHTML = span.innerHTML;
  originalHighlights.push({ element: span, html: originalHTML, classes });
  
  // Remove classes from the span
  span.className = '';
  
  // Split text into words (preserving spaces) and wrap each in a span
  const words = span.textContent.split(/(\s+)/);
  span.innerHTML = words
    .map((word) => `<span class="${classes}">${word}</span>`)
    .join('');
});

// Render canvas here

// Restore original highlight spans
originalHighlights.forEach(({ element: span, html, classes }) => {
  span.className = classes;
  span.innerHTML = html;
});
```
