### ISSUE TITLE
html2Canvas not printing chart properly in IE 11 and Doubling legend text in chrome

### ISSUE THREAD

**Issue by lifeanddesign** [niklasvh/html2canvas#614]
Hi,
I am facing two issues with html2canvas when print a fusion svg chart.

Issue 1:-
In IE 11 it doesn't print properly, screen is attached.

Issue 2:-
In Chrome the legend text are doubling itself.

These are the files which I have used so far.

html2canvas-5.0.js
html2canvas.svg.js
rgbcolor.js
StackBlur.js
canvg.js

IE 11:-

![ie11-print](https://cloud.githubusercontent.com/assets/12933153/8300401/23f7f39e-19a2-11e5-8a38-51e67c303b7f.png)

Chrome :-

![text-doubling](https://cloud.githubusercontent.com/assets/12933153/8300492/1860b984-19a3-11e5-83ef-d8d0f92d56be.png)

**Comment by lifeanddesign** [comment]
Text doubling issue us fixed.
I commented out 
var size = container.parent.css('fontSize');
in html2canvas.js 
and the issue is fixed.

but IE 11 issue is still there, please help to fix that.

**Comment by danZzyy** [comment]
I am also experiencing a similar issue screenshoting a bar graph. I got it working in Chrome and Firefox but IE renders incorrectly.

**Comment by 791182746** [comment]
Caused by an issue in html2canvas generating the text elements twice.
Apply this patch to fix until this pull request is incorporated in a html2canvas release:

NodeParser.prototype.getChildren = function(parentContainer) {
return flatten([].filter.call(parentContainer.node.childNodes, renderableNode).map(function(node) {
var container = [node.nodeType === Node.TEXT_NODE && !(node.parentNode instanceof SVGElement) ? new TextContainer(node, parentContainer) : new NodeContainer(node, parentContainer)].filter(nonIgnoredElement);
return node.nodeType === Node.ELEMENT_NODE && container.length && node.tagName !== "TEXTAREA" ? (container[0].isElementVisible() ? container.concat(this.getChildren(container[0])) : []) : container;
}, this));
};

**Comment by NPC** [comment]
@791182746 which PR do you refer to, this one?
