### ISSUE TITLE
Export leaflet map with svg overlay doesnt not show while using IE

### ISSUE THREAD

**Issue by JAPiasente** [niklasvh/html2canvas#661]
I am trying to export a map from leaflet with an svg overlay on top of the map.  When I export using Firefox, or Chrome it works as wanted.  But if I use i.e. it does not show up at all, or is shifted from where it is supposed to be.  I have a jsfiddle to illustrate what is happening.

http://jsfiddle.net/japiasente/7ybndo5L/

**Comment by CraigVA** [comment]
When the SVG wasn't showing for me in IE, the log said that the images wouldn't display because html2canvas.svg.js wasn't loaded.   I switched to the version on cloudflare instead of rawgit, and then the SVG layer showed up (although not in the right place at first).

I included my code to set the SVG viewport to the same as the map and remove the SVG transformation on svg.leaflet-zoom-animated, since html2canvas doesn't handle SVG transformations well. That got the circles to show up up in the right place.

Then the polygons are on a separate svg layer than leaflet-zoom-animated, so I had to adjust the code to handle that layer too.  I put the leaflet-zoom-hide class on the svg element instead of the g element to make it easier to access in the export code.  html2canvas doesn't work well in IE when transform or left/top properties are set on a SVG (or g) layer, so I removed all of those and set it to be the same as the map extent.

http://jsfiddle.net/wemxxfgo/5/

Also I got a console error that zoom was undefined on line 57, but it didn't seem to cause any problems.
