### ISSUE TITLE
Base href

### ISSUE THREAD

**Issue by jaggedsoft** [niklasvh/html2canvas#677]
First of all, I LOVE THIS LIBRARY!! I am very excited if you can't tell. You did an awesome job.

My page contains this code:
`<base href="//example.com">`

However, when I take the screenshot it tries to load the pictures from the current location, not example.com
Any ideas? Thanks again. Great work.

**Comment by Eseperio** [comment]
I have the same problem. It is because getComputedStyle returns wrong url. I actually made this change in (v0.5.0-beta3)

     1624: NodeContainer.prototype.parseBackgroundImages

to make it work for my project. **Beware this is not a real solution**. I´m making screenshots from the same domain, and only one level up. So this works for me until i found a better solution.

    var backendFolder=location.pathname.split("/"),
    bf=backendFolder[backendFolder.length-2];
    return this.backgroundImages || (this.backgroundImages =  parseBackgrounds(this.css("backgroundImage").replace(bf,"")));

**Comment by niklasvh** [comment]
Is this still an issue with [v1.0.0](https://github.com/niklasvh/html2canvas/releases)? If so, could you please share an example on [jsfiddle](http://jsfiddle.net/az5j0766/).
