### ISSUE TITLE
SVGs not loaded via proxy, causing tainted canvas

### ISSUE THREAD

**Issue by Paratron** [niklasvh/html2canvas#803]
Hi,
I had the issue that html2canvas would _not_ use the given proxy script to fetch SVG images. I don't know why it was built this way, but the [code in imageloader.js](https://github.com/niklasvh/html2canvas/blob/master/src/imageloader.js#L60) would never allow an SVG to be fetched by the proxy.

This causes the canvas to be tainted - even when `allowTaint` was set to false. I updated the method to only load SVGs directly, when no proxy script has been defined.

I already created pull request #802 if you want to pull the fix into the project.

**Comment by ocke** [comment]
I ran into the same problem! I have a svg file in a new browser.

This line: https://github.com/niklasvh/html2canvas/blob/master/src/imageloader.js#L63
`if (this.isSVG(src) && !this.support.svg && !this.options.allowTaint) {`
is `falsy` because of `this.support.svg`. Which is fine.
However, this line:
` } else if (this.isSameOrigin(src) || this.options.allowTaint === true || this.isSVG(src)) {`
 then is true, and loads our svg with cors set to `false` which per definition taints the canvas :|.

Questions:
- I assume SVGContainer is for browser that don't support SVG?
- Why load an SVG with cors false?

**Comment by niklasvh** [comment]
Fixed in https://github.com/niklasvh/html2canvas/commit/50608e9cd4327c3503223dca85ab7b2b2b9e629c
